DOMAIN_LEXICONS = {
    "computerized_systems": {
        "strong_tokens": [
            "computerized system",
            "computerised system",
            "csv",
            "computer system validation",
            "system validation",
            "validation of computerized systems",
            "electronic records",
            "electronic signatures",
            "audit trail",
            "access control",
        ],
        "secondary_tokens": [
            "software",
            "hardware",
            "infrastructure",
            "configuration",
            "user requirements",
            "urs",
            "functional specification",
            "design specification",
            "change control",
            "security",
            "backup",
            "restore",
            "data backup",
            "disaster recovery",
            "privilege",
            "role-based",
            "authentication",
            "authorization",
            "traceability",
            "vendor",
            "supplier",
            "periodic review",
        ],
        "negative_tokens": [
            "capa",
            "corrective action",
            "preventive action",
            "deviation investigation",
            "oos",
            "out of specification",
            "adulteration",
        ],
        "min_strong": 1,
        "min_secondary": 2,
    },
    "data_integrity": {
        "strong_tokens": [
            "data integrity",
            "alcoa",
            "alcoa+",
            "attributable",
            "legible",
            "contemporaneous",
            "original",
            "accurate",
            "audit trail",
            "metadata",
            "data governance",
            "good documentation practices",
        ],
        "secondary_tokens": [
            "complete",
            "consistent",
            "enduring",
            "available",
            "record retention",
            "retention",
            "raw data",
            "true copy",
            "data governance",
            "gdp",
            "record",
            "documentation practices",
            "access control",
            "user access",
            "backup",
            "restore",
            "time stamp",
            "timestamp",
            "controlled records",
            "record controls",
            "backup and restore",
            "audit trail review",
            "access rights",
            "user privileges",
            "attributable legible",
            "contemporaneous original",
        ],
        "negative_tokens": [
            "cleaning validation",
            "process validation",
            "iq",
            "oq",
            "pq",
            "installation qualification",
            "operational qualification",
            "performance qualification",
        ],
        "min_strong": 1,
        "min_secondary": 2,
    },
    "deviations": {
        "strong_tokens": [
            "deviation",
            "nonconformance",
            "non-conformance",
            "departure",
            "discrepancy",
            "incident",
            "investigation",
            "root cause",
            "deviation handling",
            "deviation management",
            "investigation report",
            "impact assessment",
            "capa",
            "oos investigation",
        ],
        "secondary_tokens": [
            "impact assessment",
            "assessment",
            "immediate action",
            "containment",
            "corrective action",
            "preventive action",
            "capa",
            "disposition",
            "documentation",
            "record",
            "batch impact",
            "product impact",
            "qms",
            "classification",
            "disposition decision",
            "qa approval",
            "quality unit",
            "documented",
            "evaluate impact",
            "implement capa",
            "documented fully",
            "highest priority",
        ],
        "negative_tokens": [
            "audit trail",
            "electronic records",
            "electronic signatures",
            "computer system validation",
            "computerized system",
        ],
        "min_strong": 1,
        "min_secondary": 2,
    },
    "equipment_qualification": {
        "strong_tokens": [
            "qualification",
            "equipment qualification",
            "equipment",
            "analytical equipment qualification",
            "iq",
            "oq",
            "pq",
            "installation qualification",
            "operational qualification",
            "performance qualification",
            "instrument qualification",
            "system qualification",
            "qualification plan",
            "qualification protocol",
            "qualification report",
            "protocol/plan",
        ],
        "secondary_tokens": [
            "urs",
            "user requirements",
            "acceptance criteria",
            "calibration",
            "maintenance",
            "verification",
            "validation plan",
            "protocol",
            "documented evidence",
            "intended use",
            "critical equipment",
            "installation",
            "operational",
            "performance",
            "commissioning",
            "verification",
            "requalification",
            "periodic qualification",
            "intended purpose",
            "internal documentation",
            "criteria and limits",
            "summarized and reported",
            "document/report",
            "original plan",
            "approved plan",
            "reduced testing",
            "reduced document",
        ],
        "negative_tokens": [
            "annual product review",
            "product quality review",
            "pqr",
            "apr",
            "trending",
        ],
        "min_strong": 1,
        "min_secondary": 2,
    },
    "apr": {
        "strong_tokens": [
            "annual product review",
            "product quality review",
            "apr",
            "pqr",
            "annual review",
            "product review",
            "quality review",
            "product quality review report",
            "investigations",
            "included in the review",
        ],
        "secondary_tokens": [
            "trending",
            "trend",
            "batch review",
            "complaints",
            "deviations",
            "oos",
            "stability",
            "stability data",
            "process performance",
            "product quality",
            "quality metrics",
            "corrective actions",
            "capa",
            "change control",
            "recalls",
            "batch records",
            "manufacturing process",
            "process changes",
            "quality system",
            "rejections",
            "returns",
            "investigations",
            "yield",
            "critical quality attributes",
            "specification",
            "batch release",
            "review frequency",
            "audit trail review",
        ],
        "negative_tokens": [
            "audit trail",
            "electronic signatures",
            "computerized system validation",
            "computer system validation",
            "access control",
        ],
        "min_strong": 1,
        "min_secondary": 2,
    },
    "validation": {
        "strong_tokens": [
            "process validation",
            "validation lifecycle",
            "continued process verification",
            "stage 1",
            "stage 2",
            "stage 3",
            "validation master plan",
            "vmp",
            "cleaning validation",
            "cleaning procedure",
            "revalidation",
            "validated state",
            "quality unit review",
            "process variability",
            "fit for its intended use",
        ],
        "secondary_tokens": [
            "protocol",
            "validation protocol",
            "validation report",
            "qualification",
            "verification",
            "commercial distribution",
            "process performance",
            "ppq",
            "cpv",
            "acceptance criteria",
            "quality, safety, and efficacy",
            "designed or built into the product",
        ],
        "negative_tokens": [],
        "min_strong": 1,
        "min_secondary": 2,
    },
}
